plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.jefersonai'
    compileSdk 35

    defaultConfig {
        applicationId 'br.com.jefersonai'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '0.2'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
}
